### ISSUE TITLE
Merge UnitVector3D and Vector3D

### ISSUE THREAD

**Issue by AQuentin2033** [mathnet/mathnet-spatial#100]
Proposal to merge these two classes in order to provide better generalization within the library.  The small benefit of having compile time assistance to differentiating normalized vectors from non normalized vectors is perhaps better solved by having a code analyser which checks for it.

**Comment by JohanLarsson** [comment]
I like `UnitVector3D` but chances are I'm the only one on this planet.

**Comment by cdrnet** [comment]
What if the type was called `Direction3D` instead of `UnitVector3D`, and there was also a `Direction2D` type?

**Comment by AQuentin2033** [comment]
That there is a entity which represents direction makes sense. and definitely should be matched in 2D land

**Comment by cdrnet** [comment]
The semantics of such a type would be different to a unit vector though. While it would imply that the length of the equivalent vector with the same parameters would not be relevant, it would not necessarily force it to unit length, and thus also lose some of its properties and thus computational benefits.

Maybe a direction is more like a role or context, which every vector (with matching dimensions, and other than zero) can support, e.g. by implementing a C# interface like IDirection3D. This could make some APIs a bit clearer, but not sure whether this is actually useful in practice.

**Comment by AQuentin2033** [comment]
Thinking about this some more.  I'm no longer sure having a direction makes sense.  While it is a concept in itself, the practicalities of how it is represented don't particularly make such an object suitable for a stand alone code entity.  In c# interfaces cannot be paired with usage constraints so even an interface like IDirection3D wouldn't be able to enforce the data, only the calling - which might lead to even more calls to normalize() for safety on output.

When it comes to compile time assistance to avoid a check of the vector length, I don't particularly see this as a good value proposition vs maintaining an extra class (or 2 if we implemented UnitVector2D.  But then again, I'm updating documentation and not thanking the compiler for catching a coding error so I surely have some bias here.  Seriously tho, I wonder how often people attempt to use vectors when they meant to use a unitvector, and if the method overloads support both (one with auto normalize) would they necessarily notice the opportunity for a small optimization?

**Comment by AQuentin2033** [comment]
Ok lets leave it alone for now.
