### ISSUE TITLE
IFormatProvider for Angle

### ISSUE THREAD

**Issue by AQuentin2033** [mathnet/mathnet-spatial#110]
Proposal to create a FormatProvider for Angle which can output angles in their various string formats
This would replace the use of Degrees and Radians classes and eliminate the final use of IAngleUnit

**Comment by JohanLarsson** [comment]
Can you write some pseudo code for what using it would look like?

**Comment by AQuentin2033** [comment]
Something like
```
Console.WriteLine("Custom formatting with I0:        " +
         String.Format(new AngleFormatter(), "{0:D0}", angle));
Console.WriteLine("Custom formatting with I0:        " +
         String.Format(new AngleFormatter(), "{0:R3}", angle));

//    Custom formatting with D0:        180°
//    Custom formatting with R3:        23.234 rad
```

Could also imagine including options for writing it out in Sexagesimal, Turns or Gons if we were feeling creative.

I suppose would also need to change the default ToString on Angle to call this.

**Comment by AQuentin2033** [comment]
As this change was rejected - closing issue.
