### ISSUE TITLE
.Net 4.0

### ISSUE THREAD

**Issue by SimonGubler** [mathnet/mathnet-spatial#12]
Hi

According to https://www.nuget.org/packages/MathNet.Spatial/ the NuGet-package should be installable with .Net 4.0. But when I tried to install it on a .Net 4.0-project with the commando
"Install-Package MathNet.Spatial -Pre"
the installation failed. After I changed the project to .Net 4.5, the installation succeeded.

Can you change the NuGet-package so that the installation works on a .Net 4.0-project? That would be very helpful.

Kind regards

Simon

**Comment by cdrnet** [comment]
It may also be that the description in the NuGet package is wrong, need to check.

**Comment by cdrnet** [comment]
Turns out we did not actually use any .Net 4.5 features, so I've downgraded it to .Net 4.0.
