### ISSUE TITLE
Vector3D.AngleTo-implementation sometimes returns NaN

### ISSUE THREAD

**Issue by SimonGubler** [mathnet/mathnet-spatial#13]
Hi

The following test fails:

      Vector3D v1 = new Vector3D(-1.0, -1.0, 1.0);
      Vector3D v2 = new Vector3D(-1.0, -1.0, 1.0);
      var angle = v1.AngleTo(v2);
      Assert.AreEqual(0, angle.Degrees);

For the two equal vectors, AngleTo returns an angle with NaN as value. The reason lies in the AngleTo-method of UnitVector3D:

        public Angle AngleTo(UnitVector3D v)
        {
            var dp = this.DotProduct(v);

            var angle = Math.Acos(dp);
            return new Angle(angle, AngleUnit.Radians);
        }

The dp-value is slightly above 1. This value is invalid for the Math.Acos-function which causes it to return NaN. The reason for the dp-value are rounding errors when the Vector3D-objects are converted into UnitVector3D-objects during the normalization.

The same error happens when the vectors are opposite, in that case dp is below -1.

A solution would be to check if dp is above 1 or below -1. In that case the angle must be 0° or 180°.

        public Angle AngleTo(UnitVector3D v)
        {
            var dp = this.DotProduct(v);

            if (dp > 1)
            {
              return Angle.FromDegrees(0);
            }
            if (dp < -1)
            {
              return Angle.FromDegrees(180);
            }

            var angle = Math.Acos(dp);
            return new Angle(angle, AngleUnit.Radians);
        }

Kind regards

Simon

**Comment by JohanLarsson** [comment]
Thank you for the testcase!

**Comment by JohanLarsson** [comment]
[this](https://github.com/mathnet/mathnet-spatial/commit/64c8017a75775cf678c23b0cfe6c0b3a5c582bc5) should fix it. Leaving it open a couple of days in case I missed something.
