### ISSUE TITLE
Latest MathNet.Numerics dependency

### ISSUE THREAD

**Issue by SkinnySackboy** [mathnet/mathnet-spatial#154]
Hi,

Is anyone aware of when there will be an update to this package, just to bring it in line with the latest .NET Standard MathNet.Numerics package? 

Cheers!

**Comment by JohanLarsson** [comment]
We have been working on cleaning things up and plan was to make a release. We just need to figure out the tooling and the required steps.

**Comment by SkinnySackboy** [comment]
Awesome thanks - do you know roughly when that might be? Do you think it will happen in the next couple of months or so?

Cheers!

**Comment by JohanLarsson** [comment]
We should get it done this week or today but I can't promise because I'm a bit stuck with the tooling around it.

**Comment by SkinnySackboy** [comment]
Ace thanks!

**Comment by cdrnet** [comment]
I may be able to help if needed

**Comment by JohanLarsson** [comment]
@cdrnet We pinged you in chat a couple of times but I guess you don't check gitter much.

**Comment by cdrnet** [comment]
Sorry, I don't use gitter.

**Comment by Jones-Adam** [comment]
I can also help if needed.  I believe the steps necessary are:

1. Update from Numerics 4.0.0 to 4.4.0 (and check if there are any common build changes to merge)
2. Integrate the Analysers and Codefixes into the nuget package generation
3. Fix issue with broken Benchmark paket references
4. Fix issue with obsolete Parser references in coordinatesystem 
5. have @cdrnet run "build all sign" and "build publish"

I can do 1 & 3 if its helpful.  2 I don't really know enough about nuget to do this without research.  4 - this one is yours @JohanLarsson I believe you wanted to do something different to what I previously proposed.

**Comment by SkinnySackboy** [comment]
Does anyone know this might be updated? Is there anything I can do to help as we have independent requirements which rely on the latest (.NET Standard) version of MathNet.Numerics?

**Comment by JohanLarsson** [comment]
@Jones-Adam For 4 I say ship as is.

**Comment by SkinnySackboy** [comment]
Many thanks @Jones-Adam much appreciated. I'll do this for now - hopefully someone will be able to officially publish a NuGet package officially soon.

**Comment by JohanLarsson** [comment]
We want the analyzers as they fix some breaking changes.

**Comment by SkinnySackboy** [comment]
Hi guys, is there any plan to build an official version of this and publish this on Nuget? Cheers!

**Comment by JohanLarsson** [comment]
We should do it of course. I'm stuck at figuring out how to publish what we currently have.

**Comment by chitsaw** [comment]
Would love to see an official NuGet package with .NET Standard support too. @JohanLarsson let us know if there is anything specific we can do to help.
