### ISSUE TITLE
System.MissingMethodException CoordinateSystem.CreateMappingCoordinateSystem

### ISSUE THREAD

**Issue by andrzejmy** [mathnet/mathnet-spatial#156]
Hello

I am using the library version 0.4 and latest 4.4.1 Math.Net.Numerics. I am trying to call method:

`TransformCoordinateSystem = CoordinateSystem.CreateMappingCoordinateSystem(GlobalCoordinateSystem, LocalC
oordinateSystem);`

But got following exception:
System.MissingMethodException - MathNet.Numerics.LinearAlgebra.Matrix`1.ToColumnWiseArray()'.'

Could you help me? I can write some test for these rotation if needed but I believe there is some inconsistent with the Math.Net.Numerics library?

**Comment by JohanLarsson** [comment]
`ToColumnWiseArray` was removed from `MathNet.Numerics` IIRC. Using an older version until we get the updated spatial out is the only way I think.

**Comment by andrzejmy** [comment]
Thanks a lot for quick support! With the latest 3.x is working!
