### ISSUE TITLE
Use PublicApiAnalyzer

### ISSUE THREAD

**Issue by JohanLarsson** [mathnet/mathnet-spatial#159]
https://www.nuget.org/packages/PublicApiAnalyzer/

**Comment by cdrnet** [comment]
What does it do? Somehow both nuget packages and the project readme completely forgot to mention what this is all about :).

**Comment by JohanLarsson** [comment]
Oh, it just dumps the public API to a text file. Looks like [this](https://github.com/GuOrg/Gu.Wpf.NumericInput/blob/master/Gu.Wpf.NumericInput/PublicAPI.Unshipped.txt)

Adding it is quick, wrote the issue as a reminder.
