### ISSUE TITLE
Point3D ItersectionOf() typo

### ISSUE THREAD

**Issue by mattj23** [mathnet/mathnet-spatial#16]
The Point3D class appears to have a typo in the IntersectionOf method name.  

```c#
        public static Point3D ItersectionOf(Plane plane1, Plane plane2, Plane plane3)
        {
            var ray = plane1.IntersectionWith(plane2);
            return plane3.IntersectionWith(ray);
        }

        public static Point3D ItersectionOf(Plane plane, Ray3D ray)
        {
            return plane.IntersectionWith(ray);
        }
```

I fixed it in the method names and the unit tests in a fork, or I'll happily add renamed methods side-by-side to not break the semantics and add them to the unit tests if you'd like.

**Comment by cdrnet** [comment]
Thanks! Could you open a PR with the fix? This project is still in an alpha phase so it's ok to break compatibility, no need for side-by-side functions.
