### ISSUE TITLE
NuGet package must not include reference to PublicApiAnalyzer nor to StyleCop.Analyzers

### ISSUE THREAD

**Issue by cdrnet** [mathnet/mathnet-spatial#161]
Looks like a packaging issue.

**Comment by JohanLarsson** [comment]
Paket has `excludedGroups`

Add:
```
excludedgroups
  build
  Analyzers
```

To paket.template

**Comment by cdrnet** [comment]
I'm actually using the .Net SDK directly to create the packages at this point - but I expect it has a similar feature. Thanks for the pointer!

**Comment by JohanLarsson** [comment]
I never figured out how to exclude using `dotnet pack`

**Comment by cdrnet** [comment]
If needed we can use Paket for packing. I wished to get a bit closer to the standard tooling, but I actually have other issues with dotnet pack as well (e.g. even despite `--no-build` it still recreates the dlls in some cases, which messes with code signing).

**Comment by JohanLarsson** [comment]
Nice if standard tooling can be used of course.

**Comment by Jones-Adam** [comment]
with regard to dotnet pack repacking, have a look at 
https://stackoverflow.com/questions/50232375/how-to-dotnet-pack-an-already-compiled-project/50233550#50233550
if the project file contains an alternate build path, dotnet pack won't find it and will build it again

**Comment by li0nsar3c00l** [comment]
Please make sure adding the privateassets options, so they won't flow to any project referencing this library and force the dev to deal with different stylecop warnings

**Comment by ugumba** [comment]
Thanks for your efforts!
While waiting for an updated beta nuget, is there any way to avoid these analyzers running on my code?  
I've tried various combinations of ExcludeAssets/PrivateAssets/IncludeAssets with no success - I keep getting warnings in the hundreds.  It's very annoying, to put it mildly.

**Comment by li0nsar3c00l** [comment]
Same here. As far as I understood the concept, there is no option to prevent this, if it hasn't been done in the original project. And apparently, according to https://github.com/mathnet/mathnet-spatial/issues/158, releasing isn't that easy yet.
