### ISSUE TITLE
LineSegment2D.TryIntersect should intersect segments, not lines

### ISSUE THREAD

**Issue by imlex** [mathnet/mathnet-spatial#166]
LineSegment2D.TryIntersect returns true even if lines crosses in point located out of segments.

**Comment by JohanLarsson** [comment]
Thanks for reporting, do you have some sample code we can use in a test?

**Comment by imlex** [comment]
I've created pull request #167

**Comment by cdrnet** [comment]
Thanks! Closed by #167.
