### ISSUE TITLE
I would like to contribute to the project

### ISSUE THREAD

**Issue by kabircosta** [mathnet/mathnet-spatial#188]
I just visited the website: _https://spatial.mathdotnet.com/Contributing.html_
I would like to contribute to the project, adding a little bit to the XML documentation with examples and adding new methods of geometric relations (perpendicularism, parallelism, collinearity, etc.)

How is the standard procedure for the test project (Spatial.Tests)? Can I modify it at will?
I would like to test the methods and compare them with my Geogebra files. Can I add the geogebra files within the Spatial.Tests project in a separeted folder?

Sorry for the basicity of my question, this is the first time I have contributed to a project. Any suggestion is welcome.

**Comment by kabircosta** [comment]
@cdrnet

**Comment by jkalias** [comment]
Hi @kabircosta ,

Improving the test coverage is something that I am really fond of. You can create new test files in the test project or extend the existing ones. I think that comparison with external/other software (like Geogebra) would definitely be something worth pursuing.

I am not really familiar with the file format of Geogebra. I think that providing a snapshot in the PR of what you are trying to compare would for sure help.

Let me know if you need more help.

**Comment by kabircosta** [comment]
Hello @jkalias, thank you for your response. Do you use any software to verify and validate calculations when generating tests or visualizing vectors, points and other 3D and 2D geometries?

**Comment by jkalias** [comment]
Hi @kabircosta and thanks again for your time and effort, making Spatial better.

I use an internal tool at my employer, but I recently came across [Geogebra](https://www.geogebra.org/calculator) which is quite handy.

**Comment by jkalias** [comment]
Nothing more to do here
