### ISSUE TITLE
Consider to use Microsoft.Bcl.Simd internally

### ISSUE THREAD

**Issue by cdrnet** [mathnet/mathnet-spatial#2]
See:
- [Microsoft.Bcl.Simd NuGet package](https://www.nuget.org/packages/Microsoft.Bcl.Simd)
- [RyuJIT: The next-generation JIT compiler for .NET](http://blogs.msdn.com/b/dotnet/archive/2013/09/30/ryujit-the-next-generation-jit-compiler.aspx)
- [SIMD Sample](http://code.msdn.microsoft.com/SIMD-Sample-f2c8c35a)
- [SIMD - Wikipedia](https://en.wikipedia.org/wiki/SIMD)

Maybe it makes sense to use their fixed-sized vectors, maybe not.

(low priority)

**Comment by jkalias** [comment]
Closed as no relevant anymore. [Microsoft.Bcl.Simd](https://www.nuget.org/packages/Microsoft.Bcl.Simd) does not exist anymore, and the latest update was on 11.04.2014

**Comment by jkalias** [comment]
Not relevant anymore. [Microsoft.Bcl.Simd](https://www.nuget.org/packages/Microsoft.Bcl.Simd) does not exist anymore, and the latest update was on 11.04.2014
