### ISSUE TITLE
Get X and Y values for Point2D?

### ISSUE THREAD

**Issue by minystreem56** [mathnet/mathnet-spatial#240]
I can't figure out how to get the x and y cordnets of a point2d, I have tried point.getX(), point.getx(), point.x, point.X, getX(point), getx(point), but none of them work, any ideas?

**Comment by jkalias** [comment]
`point.X`

**Comment by minystreem56** [comment]
I tried that, but it did not work

**Comment by jkalias** [comment]
![image](https://github.com/mathnet/mathnet-spatial/assets/942804/be5ab250-97f8-4745-8be9-71030915af17)
I can't really believe that

**Comment by minystreem56** [comment]
Thats really werid. I can try it, but I swear it didn't work. Thanks!

**Comment by jkalias** [comment]
No worries. I would also close the issue once you figure this out, perhaps writing a comment for future reference

**Comment by minystreem56** [comment]
Werid, I just tried that and I got this error:
`error CS1061: 'Point2D?' does not contain a definition for 'X' and no accessible extension method 'X' accepting a first argument of type 'Point2D?' could be found (are you missing a using directive or an assembly reference?)`

**Comment by minystreem56** [comment]
Ok so it works, but I am using the IntersectWith function which returns a nullable point2d, so the problem may lie with the fact that it is nullable?

**Comment by jkalias** [comment]
That's what got me worried in your previous reply, that the `Point2D` was nullable. No, the `IntersectWith` should indeed return nullable, since there is also the possibility, that no intersection occurs.

I am guessing you are using `Line2D.IntersectWith`, so when the lines are parallel there is no intersection.

**Comment by jkalias** [comment]
@minystreem56  Would you mind if I close this issue now?

**Comment by minystreem56** [comment]
No, I do not mind
