### ISSUE TITLE
PolyLine2D/3D and Polygon2D classes

### ISSUE THREAD

**Issue by mattj23** [mathnet/mathnet-spatial#33]
In my work I make common use of 2D and 3D polylines (a series of 2d or 3d points connected by line  segments) and 2D polygons (similar to a polyline except that the first and last points are connected, enclosing an area).  

I've written classes for my own use that handle these particular constructs and support basic operations, such as computation of length and area, projection of points onto them, convex hulls, etc, as well as unit tests for these operations.

Is this something that fits within the scope of Mathnet.Spatial?  If so, if I were to create a branch with these features in it would there be interest in reviewing it?

**Comment by JohanLarsson** [comment]
Sounds awesome!

**Comment by mattj23** [comment]
Take a look at this...the Polygon2D class is built on top of it, and the PolyLine3D class is essentially a 3D version of the same thing.

https://github.com/mattj23/mathnet-spatial/blob/issue33_polylines/src/Spatial/Euclidean/PolyLine2D.cs

**Comment by JohanLarsson** [comment]
Can you make a PR with it? Nicer to review it that way.
