### ISSUE TITLE
Inconsistent return type for Matrix3D.RotationAround{X|Y|Z}Axis(angle) #question

### ISSUE THREAD

**Issue by olvd** [mathnet/mathnet-spatial#39]
Is there a reason for 
`MathNet.Spatial.Euclidean.Matrix3D.RotationAround{X|Y}Axis(angle)` returning a `DenseMatrix`
and
`MathNet.Spatial.Euclidean.Matrix3D.RotationAroundZAxis(angle)` returning a `Matrix<double>`
or is it just a typo?

**Comment by JohanLarsson** [comment]
This looks wrong. @cdrnet what is the most correct type here?
Thanks for creating the issue.

**Comment by cdrnet** [comment]
Yes, I'd expect a `Matrix3D` as well, in both cases.
