### ISSUE TITLE
Release a signed version

### ISSUE THREAD

**Issue by tongbong** [mathnet/mathnet-spatial#44]
Hello guys,
first of all thank you for your effort on this project.
I was wondering if you had plans to release a signed version of spatial like numerics 
https://www.nuget.org/packages/MathNet.Numerics.Signed/
Cheers,
Francois

**Comment by cdrnet** [comment]
We had no plans so far yet, but there is no technical reason not to provide it (as you've already noticed we do this in Numerics as well).

**Comment by tongbong** [comment]
No problem, I have a tough client that only integrates signed libraries.
Anyway, signing a lib is not a hell of a job. So we will keep doing that by signing a clone.

**Comment by JensChrMikkelsen** [comment]
I can see the issue is closed but I'm the same situation, needing a signed version of Spatial.

**Comment by cdrnet** [comment]
We finally publish strong named assemblies, in MathNet.Spatial.Signed.
