### ISSUE TITLE
UAP framework support

### ISSUE THREAD

**Issue by joelday** [mathnet/mathnet-spatial#45]
Would be nice to be able to use for the new Universal Windows framework. Thanks!

**Comment by cdrnet** [comment]
According to the [.NET Platform Standard](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md) it seems supporting `netstandard <= 1.4` would cover UAP apps?

**Comment by joelday** [comment]
Yep, everything is fine here. Thanks!
