### ISSUE TITLE
Coordinate system Pitch, Roll, Yaw bug

### ISSUE THREAD

**Issue by zorandragan** [mathnet/mathnet-spatial#46]
After rotating a CSY (Coordinate System) around any of axis, by using e.g. CoordinateSystem.Pitch, CSY rotates successfully, rotation matrix contains correct values. After further rotating it with the same (or any other) angle, rotation matrix is not showing correct results, at least what I was expecting. It seems like it rotates again from the original state of a CSY, that it had before the first rotation. After the second rotation CSY again has as same rotation matrix as after the first rotation.

**Comment by ErikWahlstrom** [comment]
Can you share some code that shows the error behavior?

**Comment by zorandragan** [comment]
@ErikWahlstrom 

Here is the test. The matrices are the same, although the CSY was rotated twice around the Y axis.
`CoordinateSystem testCSY = new CoordinateSystem(new Point3D(400, 500, 600), new UnitVector3D(1, 0, 0), new UnitVector3D(0, 1, 0), new UnitVector3D(0, 0, 1));
            Angle alpha = new Angle(90, new Degrees());
            //Rotates around Y
            testCSY = CoordinateSystem.Pitch(alpha);
            Matrix<double> rotMatrix1st = CoordinateSystem.GetRotationSubMatrix(testCSY);
            //Rotates around Y again
            testCSY = CoordinateSystem.Pitch(alpha);
            Matrix<double> rotMatrix2nd = CoordinateSystem.GetRotationSubMatrix(testCSY);
            bool eq = false;
            for (int i = 0; i < 3; i++)
                for (int j = 0; j < 3; j++)
                    eq = rotMatrix1st.Storage.At(i, j) == rotMatrix2nd.Storage.At(i, j);            
            Assert.IsTrue(eq, "Matrices are equal");`

**Comment by ErikWahlstrom** [comment]
Not sure if I entirely understand your intention but I think you are using it wrong (at least from how the API is designed now). Pitch is a static method which returns a new immutable coordinate system each time.  So in order to Pitch it 2 times alpha you would want to do CoordinateSystem.Pitch(alpha * 2) for the second coordinatesystem. If you want multiple rotations (yaw, pitch roll) you can use CoordinateSystem.Rotation(yaw, pitch, roll).

**Comment by zorandragan** [comment]
@ErikWahlstrom 
I see now that I was using it wrong. I need a CSY that can have a "state", but for that I guess I would need to create my own wrapper class. Thanks very much for the support.
