### ISSUE TITLE
Plane: documented constructor missing

### ISSUE THREAD

**Issue by Bernhard-Hiller** [mathnet/mathnet-spatial#49]
For the plane class, following constructor is documented:
Plane(Point3D p1, Point3D p2, Point3D p3)
but it is missing from the code.

**Comment by JohanLarsson** [comment]
The nuget package is lagging, I have not figured out how to use the fake thing yet.
@cdrnet if you have time it would be great to bump & release.

**Comment by cdrnet** [comment]
Yes, I can make a release. I've also been asked to bump to v1.0 - I'm ok with that, unless you have some concerns?

**Comment by JohanLarsson** [comment]
I would prefer to keep it at 0.x still but not a huge issue.

**Comment by cdrnet** [comment]
I've just release the current master as v0.3.0 (still 0.x but I've dropped the prerelease marker).
