### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by Hugh-walsh** [mathnet/mathnet-spatial#52]
The use of .net core is required, and will now become more important with visual studio 2017.

My personal requirement is to be able to use mathnet-spatial with docker so that we can scale up and down the number of calculation engines.  

Note: this is currently blocked by:
https://github.com/mathnet/mathnet-numerics/issues/386

But could be trialed in a branch by using the temporary solution in:
MathNet.Numerics.Core

**Comment by aaronwestre** [comment]
Is anyone working on this issue? The Numerics project supports .NET Standard 2.0 as a build target. Are there any problems with trying that for Spatial? I could give it a try if no one else is actively pursuing it.

**Comment by JohanLarsson** [comment]
No one is working on it that I know of, go ahead and make a PR if you have time to do it.

**Comment by AQuentin2033** [comment]
netstandard 1.3 and netstandard 2.0 support added in #125

**Comment by rpawlaszek** [comment]
Hi @Jones-Adam. Do you plan to publish the netstandard version (both: non-signed and signed) via NuGet anytime soon?

**Comment by Jones-Adam** [comment]
@rpawlaszek Since I don't own this project and have no rights to even include my merge with the .netstandard 2.0 support I don't really know what to do here.   I don't think @cdrnet would appreciate it if I published a "rogue" nuget package :)

**Comment by cdrnet** [comment]
I've just upgraded Math.NET Symbolics to support .Net Standard 2.0 yesterday, Math.NET Spatial is next on the list (in parallel there is also an open branch in Numerics that experiments with integrating Spatial directly into Numerics - but not clear yet what option is better).

**Comment by rpawlaszek** [comment]
@Jones-Adam @cdrnet thank you. The netstandard Math.NET Spatial would be very helpful for me right away. Regarding the integration - I don't have any preference here, but again my usage is very limited for now.

**Comment by cdrnet** [comment]
I've released [v0.5.0-beta04](https://www.nuget.org/packages/MathNet.Spatial/0.5.0-beta04) with support for .Net Standard 1.3 and 2.0 (and .Net Framework 4.0) and higher. Note that the beta does not include the analyzers yet.
