### ISSUE TITLE
Expanding Plane Geometry

### ISSUE THREAD

**Issue by AQuentin2033** [mathnet/mathnet-spatial#58]
Hi,

I would like to expand Mathnet-spatial to include more aspects of plane geometry (2D).  In particular adding support for different types of lines and shapes and make it a first class feature of the library.  Since its a structural change to the library I thought it more polite to run it by you before sending a pull request

To this end I propose a few alterations to the namespace structure to create
Euclidean -> PlaneGeometry -> Shapes
                                               -> Lines

Into shapes the idea is to progressively add various common shape constructs (ellipses, rectangles, triangles, etc).  Into Lines would go support for various curve types (parabola, hyperbola, etc.)

A few breaking changes would be required such as renaming Line2D to LineSegment to avoid confusion with the geometric definition of a Line and moving existing 2D constructs into the new namespaces.

Perhaps it is easier to explain by showing what I suggest to change - [https://github.com/AQuentin2033/mathnet-spatial/commit/c8a0b0f483d51285386320c891491945d789d8c9](url)

Anyway would that work as a direction for you?

**Comment by JohanLarsson** [comment]
I agree that Line2D has an unfortunate name. We could mark it as `[Obsolete]` and introduce `LineSegment`.
About the namespaces I'm not sure I see a huge upside with adding that depth, no obvious name collisions come to mind. Fragmenting things could lead to half a screen of usings when using the lib, not awesome.

**Comment by AQuentin2033** [comment]
Ok, its just the list of classes gets a little long when you add in a dozen shapes and another dozen or so curve types and its easier to manage/find what you are looking for if they are grouped,  Would splitting the 2D items into a single sub namespace PlaneGeometry be an acceptable balance?  There is an argument there that users of the 2D features are not necessarily interested in the 3D operations.

**Comment by JohanLarsson** [comment]
We can have folders that are not namespaces for organizing. I think it is a good idea to keep things flat to start with. Then before release we can have a look if we should adjust things. But we should avoid breaking our friends if possible.

**Comment by AQuentin2033** [comment]
ok noted.

**Comment by JohanLarsson** [comment]
I hope this is not a no-starter for you.

**Comment by AQuentin2033** [comment]
not at all, its just more of a challenge - how/why to add new functionality takes on a different meaning if the primary focus is compatibility.

So for example with this train of thought renaming line2D is mostly petty if the only issue is its name.
instead a better patch would be to introduce lineSegement<T> where T is a line type.  So you can have any curved or straight line segment.
Then the decision to obsolete LIne2D comes when all of its current functionality is better represented in other parts of the library.

I have also seen that some other people have started (but not completed) the work of adding in basic shape support in the various forks people have made.  I will also take some small time to review what they have done with the goal to not let that work go to waste either.
