### ISSUE TITLE
Point3D references in Point2D

### ISSUE THREAD

**Issue by AQuentin2033** [mathnet/mathnet-spatial#63]
Logically a 2D point shouldn't have knowledge of higher dimensions.  If a library user wishes to convert a 2D point into a 3D point it is more likely they would wish to project the point onto a plane in 3D space which is not handled by this function.

I therefor propose to obsolete the method ToPoint3D method and the Point3D operators.

**Comment by JohanLarsson** [comment]
This sounds reasonable.
