### ISSUE TITLE
Limits of floating point

### ISSUE THREAD

**Issue by AQuentin2033** [mathnet/mathnet-spatial#79]
Sorry this is a bit long but its a complex issue...

Currently in the library it is possible to specify a tolerance when comparing two points or two angles, but not for comparing two lines or two circles.  In the case of the composites the comparisons always use the default equal operators, however due to rounding point errors this might mean ni a given context that two circles which should be considered the same are treated as different in the library.  So somehow I should be able to specify what the tolerance is in every case where a comparison is done - however as a library user I potentially have no idea what kind of operations or calculations have gone into a given comparison, so I really have no idea what a good tolerance should be.  If its just comparing values I have provided that is one thing, if its using the result of a calculation the library has performed for me, that's another.  So this leaves me with a number of potentially broken scenarios where the library either offers me no help (by asking me for a tolerance I do not know enough to provide), or at worse hinders me (by ignoring tolerances altogether and potentially hiding the accumulating errors). 

Perhaps the solution to this lies in looking at the problem from a different perspective..  Lets say I have a coordinate system which has a limit of resolution of 2 decimal places.  After which in this particular context further precision is meaningless to me.  Now I could go and preprocess every value entering and coming from the library to fit to my needs but it would be infinitely nicer if the library allowed me to specify in a single place the limits of resolution for my coordinate system (points and angles) and automatically adhered to it with any return or calculation it provided to me.
This kind of limit to the needed precision can easily be specified by the library user according to their particular context (and within the bounds of resolution of a double).  While it doesn't specifically address the errors of floating point math, it does offer a context sensitive way to make it a less significant issue

I think the most obvious place for such a thing would be static properties on CoordinateSystem and have those types which use doubles to adhere to it on return values and comparisons (but keep using the full value internally for calculations).  It could potentially allow either a fixed number of decimal places or a fixed number of overall digits to allow for maximum flexibility.

Anyway more than open to other suggestions if anyone can think of a better way to handle this.

**Comment by JohanLarsson** [comment]
We should definitely add overloads with tolerances for all types.

**Comment by AQuentin2033** [comment]
A few more inconsistencies of note: 
Quaternion uses AlmostEquals for its double comparisons,
EulerAngles uses a fixed constant of 0.000001;

**Comment by JohanLarsson** [comment]
`Quaternion` uses almost in the `Equals` method and exactly in `GetHashCode`, not ideal, easy fix.

**Comment by AQuentin2033** [comment]
Alignment of equals and gethashcode and overloads with tolerances across all types complete.  This offers the best balance for generic use of the libraries relatively low level types.
