### ISSUE TITLE
I have no idea how to use paket to update references

### ISSUE THREAD

**Issue by JohanLarsson** [mathnet/mathnet-spatial#8]
Here is what I tried:
 .\tools\paket\paket update
Updated the packages but removed ref to mathnet.numerics from projects.
> Locked version resolutions written to C:\Git\Third Party\mathnet-spatial\paket.lock
  - custom nodes for MathNet.Numerics ==> skipping
  - custom nodes for MathNet.Numerics ==> skipping

Think ^ has something to do with it.

**Comment by cdrnet** [comment]
Paket has gone a long way since - get a new version by calling fake.bootstrap.exe once.
